# $FreeBSD: src/sys/modules/msdosfs/Makefile,v 1.19 2002/11/06 13:46:59 nyan Exp $

.PATH: ${.CURDIR}/../../fs/edufs

KMOD=	edufs
SRCS=	vnode_if.h \
	edufs_ehash.c edufs_vfsops.c edufs_vnops.c

.include <bsd.kmod.mk>
